// Tracer-bullet seed data — 1 mineral (QUARTZO) with one row, hardcoded.
// Real index is generated by `scripts/extract_xlsm.py` and lives in `data/filter-index.json`.
// This file is replaced once the pipeline produces real data.

import type { FilterRow } from "@/types/mineral";

export const SEED_ROWS: FilterRow[] = [
  {
    name: "QUARTZO",
    rawName: "QUARTZO    SiO2",
    slug: "quartzo",
    type: "TECTOSSILICATOS",
    brilho: "vitreo",
    traco: "incolor",
    durezaNum: 7,
    habito: "cristais",
    luz: "transparente",
    cor: "incolor",
  },
];
